// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBma4dACP6NikVJJV869kwI58I-440EbxA',
    appId: '1:49759517990:web:67fca8fa86f1127430d5e7',
    messagingSenderId: '49759517990',
    projectId: 'video-clone-4d9ba',
    authDomain: 'video-clone-4d9ba.firebaseapp.com',
    storageBucket: 'video-clone-4d9ba.appspot.com',
    measurementId: 'G-JBLREKKSX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoYS_L3IGWkY8KfcGAKEnmBYtXT1drNdU',
    appId: '1:49759517990:android:c2dc3b9e6fbe299530d5e7',
    messagingSenderId: '49759517990',
    projectId: 'video-clone-4d9ba',
    storageBucket: 'video-clone-4d9ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvnlKGU4aSRlsRYCud9toHlxWPn3x7Mis',
    appId: '1:49759517990:ios:7cdc1a596bf8e37c30d5e7',
    messagingSenderId: '49759517990',
    projectId: 'video-clone-4d9ba',
    storageBucket: 'video-clone-4d9ba.appspot.com',
    iosBundleId: 'com.example.zoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvnlKGU4aSRlsRYCud9toHlxWPn3x7Mis',
    appId: '1:49759517990:ios:0c6ebd4eaac334a530d5e7',
    messagingSenderId: '49759517990',
    projectId: 'video-clone-4d9ba',
    storageBucket: 'video-clone-4d9ba.appspot.com',
    iosBundleId: 'com.example.zoom.RunnerTests',
  );
}
